version: '3'
services:
  dydxprotocold0:
    image: local:e2etest-dydxprotocol
    platform: linux/amd64
    entrypoint:
      - cosmovisor
      - run
      - start
      - --log_level
      # Note that only this validator has a log-level of `info`; other validators use `error` by default.
      # Change to `debug` for more verbose log-level.
      - info 
      - --home
      - /dydxprotocol/chain/.alice
      - --p2p.persistent_peers 
      - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@dydxprotocold0:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@dydxprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@dydxprotocold3:26656"
      - --bridge-daemon-eth-rpc-endpoint
      - "${ETH_RPC_ENDPOINT}"
    environment:
      - DAEMON_HOME=/dydxprotocol/chain/.alice
    volumes:
      - ../protocol/localnet/dydxprotocol0:/dydxprotocol/chain/.alice/data
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"
  
  # This is the Indexer connected node.
  # TODO: remove stake and make this a full node.
  dydxprotocold1:
    image: local:e2etest-dydxprotocol
    platform: linux/amd64
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /dydxprotocol/chain/.bob
       - --p2p.persistent_peers 
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@dydxprotocold0:26656,b69182310be02559483e42c77b7b104352713166@dydxprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@dydxprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@dydxprotocold3:26656"
       - --non-validating-full-node=true
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --indexer-kafka-conn-str
       - "kafka:9092"
    environment:
      - DAEMON_HOME=/dydxprotocol/chain/.bob
    volumes:
      - ../protocol/localnet/dydxprotocol1:/dydxprotocol/chain/.bob/data
    ports:
      - "26658:26657"
 
  dydxprotocold2:
    image: local:e2etest-dydxprotocol
    platform: linux/amd64
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /dydxprotocol/chain/.carl
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@dydxprotocold0:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@dydxprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@dydxprotocold3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
    environment:
      - DAEMON_HOME=/dydxprotocol/chain/.carl
    volumes:
      - ../protocol/localnet/dydxprotocol2:/dydxprotocol/chain/.carl/data
  
  dydxprotocold3:
    image: local:e2etest-dydxprotocol
    platform: linux/amd64
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /dydxprotocol/chain/.dave
       - --p2p.persistent_peers 
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@dydxprotocold0:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@dydxprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@dydxprotocold3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
    environment:
      - DAEMON_HOME=/dydxprotocol/chain/.dave
    volumes:
      - ../protocol/localnet/dydxprotocol3:/dydxprotocol/chain/.dave/data

  ender:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service.remote
      args:
        service: ender
    ports:
      - 3001:3001
    environment:
      - REDIS_URL=redis://redis:6379
  comlink:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service.remote
      args:
        service: comlink
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_REDIS_URL=redis://redis:6379
      - RATE_LIMIT_ENABLED=false
      - COMPLIANCE_DATA_CLIENT=PLACEHOLDER
    ports:
      - 3002:3002
  socks:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service.remote
      args:
        service: socks
    ports:
      - 3003:3003
    environment:
      - WS_PORT=3003
      - COMLINK_URL=host.docker.internal:3002
  roundtable:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service.remote
      args:
        service: roundtable
    ports:
      - 3004:3004
  vulcan:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service.remote
      args:
        service: vulcan
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - 3005:3005
